# config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proxy'
    scheme: 'https'
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['proxy:8443']
    fallback_scrape_protocol: 'http'
